# Basic Ubuntu official image with docker installed after provisioning
# Reference: https://www.vagrantup.com/docs/provisioning/docker.html

Vagrant.configure("2") do |config|
  config.vm.box_version = "20191030.0.0"
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = true
  config.vbguest.auto_update = false if Vagrant.has_plugin?("vagrant-vbguest")

  # The hostname set for the VM should only contain letters, numbers,
  # hyphens or dots. It cannot start with a hyphen or dot.
  config.vm.define "postgres-vm" do |postgres_vm|
    postgres_vm.vm.hostname = "postgres-vm"

    # This is required so that the VM can be accessed through the IP from the host
    postgres_vm.vm.network "public_network", bridge: "wlo1", ip: "192.168.1.10"

    postgres_vm.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = 2_048
      vb.cpus = 2
    end

    postgres_vm.ssh.insert_key = false
    postgres_vm.ssh.private_key_path = %w[~/.vagrant.d/insecure_private_key ~/.ssh/vagrant_vm_rsa]
    postgres_vm.vm.provision "file",
                             source: "~/.ssh/vagrant_vm_rsa.pub",
                             destination: "~/.ssh/vagrant_vm_rsa.pub"
    postgres_vm.vm.provision "shell",
                             inline: <<-SHELL
      cat /home/vagrant/.ssh/vagrant_vm_rsa.pub > /home/vagrant/.ssh/authorized_keys
    SHELL
  end
  # pgadmin4 requires username and password during installation
  # hence the script to install postgresql and pgadmin4 is executed after VM is provisioned
  # by doing ssh in to VM
  config.vm.provision "shell", path: "install_postgresql.sh"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
end
